# Generated by Django 2.1.7 on 2019-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('order_dow', models.IntegerField()),
                ('order_hour_of_day', models.IntegerField()),
                ('days_since_prior_order', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('add_to_cart_order', models.IntegerField()),
                ('reordered', models.BooleanField()),
                ('product_name', models.CharField(max_length=200)),
                ('aisle_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('aisle', models.CharField(max_length=200)),
            ],
        ),
    ]
