# Generated by Django 2.1.7 on 2019-02-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
    ]
