# Generated by Django 2.1.7 on 2019-02-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_id', models.IntegerField()),
                ('user_pick', models.CharField(max_length=200)),
                ('recommend_id', models.IntegerField()),
                ('recommend', models.CharField(max_length=200)),
            ],
        ),
    ]
